// Sample data for demo users
module.exports = [
	{
		date: '',
		userId: '',
		food: ['Pancakes', 'Fruit', 'Pizza', 'Cookies', 'Meatloaf'],
		notes: ['Tylenol'],
		poop: 0,
		sleep: {
			wakeUp: '06:30',
			nap1Start: '10:00',
			nap1End: '11:45',
			nap2Start: '15:00',
			nap2End: '17:10',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Waffles',
			'Toast',
			'Hot dogs',
			'Cereal',
			'Crackers',
			'Cookies',
			'Pot pie',
		],
		notes: ['Play date with Charlie'],
		poop: 2,
		sleep: {
			wakeUp: '07:05',
			nap1Start: '09:45',
			nap1End: '11:20',
			nap2Start: '00:00',
			nap2End: '00:00',
			bedTime: '20:30',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Cereal',
			'Cookies',
			'Apple',
			'Soup',
			'Crackers',
			'Pork roll',
			'Ice cream',
		],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '06:58',
			nap1Start: '09:40',
			nap1End: '12:10',
			nap2Start: '15:30',
			nap2End: '16:30',
			bedTime: '20:40',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Pancakes',
			'Fruit',
			'Pizza',
			'Oatmeal',
			'Crackers',
			'Pretzels',
			'Noodles',
		],
		notes: [],
		poop: 1,
		sleep: {
			wakeUp: '07:00',
			nap1Start: '09:30',
			nap1End: '11:40',
			nap2Start: '15:00',
			nap2End: '16:10',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'French toast',
			'Fruit',
			'Pancakes',
			'Orange',
			'Chicken',
			'Ice cream',
		],
		notes: ['Tylenol', 'Mothers bliss'],
		poop: 0,
		sleep: {
			wakeUp: '06:10',
			nap1Start: '09:20',
			nap1End: '11:50',
			nap2Start: '14:50',
			nap2End: '16:10',
			bedTime: '20:30',
		},
	},
	{
		date: '',
		userId: '',
		food: ['Pancakes', 'Fruit', 'Oatmeal', 'Cake', 'Cookies', 'Meatloaf'],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '06:50',
			nap1Start: '09:40',
			nap1End: '11:20',
			nap2Start: '15:20',
			nap2End: '17:00',
			bedTime: '21:10',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Waffles',
			'Yogurt',
			'Chicken fingers',
			'Crackers',
			'Fruit',
			'Ham',
		],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '07:20',
			nap1Start: '10:00',
			nap1End: '11:30',
			nap2Start: '15:00',
			nap2End: '16:10',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: ['Waffles', 'Nuts', 'Sandwich', 'Cookies', 'Pot pie'],
		notes: ['Tylenol'],
		poop: 0,
		sleep: {
			wakeUp: '06:50',
			nap1Start: '10:10',
			nap1End: '11:25',
			nap2Start: '14:40',
			nap2End: '17:00',
			bedTime: '20:30',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Cereal',
			'Toast',
			'Hot dogs',
			'Pretzels',
			'Crackers',
			'Cookies',
			'Hot dog',
		],
		notes: ['Play date with Charlie'],
		poop: 0,
		sleep: {
			wakeUp: '07:15',
			nap1Start: '09:35',
			nap1End: '11:40',
			nap2Start: '15:00',
			nap2End: '15:50',
			bedTime: '20:20',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Cereal',
			'Cookies',
			'Apple',
			'Soup',
			'Crackers',
			'Pork roll',
			'Ice cream',
		],
		notes: ['Tylenol'],
		poop: 0,
		sleep: {
			wakeUp: '06:38',
			nap1Start: '09:30',
			nap1End: '12:20',
			nap2Start: '15:00',
			nap2End: '16:40',
			bedTime: '20:20',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'French Toast',
			'Fruit',
			'Pizza',
			'Oatmeal',
			'Cookies',
			'Pretzels',
			'Noodles',
		],
		notes: [],
		poop: 1,
		sleep: {
			wakeUp: '06:00',
			nap1Start: '09:10',
			nap1End: '11:20',
			nap2Start: '15:10',
			nap2End: '16:20',
			bedTime: '20:40',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'French toast',
			'Fruit',
			'Pancakes',
			'Orange',
			'Chicken fingers',
			'Ice cream',
		],
		notes: ['Tylenol', 'Mothers bliss'],
		poop: 0,
		sleep: {
			wakeUp: '06:20',
			nap1Start: '09:30',
			nap1End: '11:40',
			nap2Start: '14:40',
			nap2End: '16:20',
			bedTime: '20:45',
		},
	},
	{
		date: '',
		userId: '',
		food: ['Pancakes', 'Eggs', 'Oatmeal', 'Cake', 'Cookies', 'Tacos'],
		notes: [],
		poop: 3,
		sleep: {
			wakeUp: '06:50',
			nap1Start: '09:20',
			nap1End: '11:50',
			nap2Start: '15:20',
			nap2End: '17:10',
			bedTime: '21:20',
		},
	},
	{
		date: '',
		userId: '',
		food: ['Waffles', 'Yogurt', 'Chicken', 'Crackers', 'Fruit', 'Pork'],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '07:00',
			nap1Start: '10:10',
			nap1End: '11:10',
			nap2Start: '15:10',
			nap2End: '16:20',
			bedTime: '21:20',
		},
	},
	{
		date: '',
		userId: '',
		food: ['Pancakes', 'Fruit', 'Pizza', 'Cookies', 'Meatloaf'],
		notes: ['Tylenol', 'Teething'],
		poop: 1,
		sleep: {
			wakeUp: '06:30',
			nap1Start: '10:00',
			nap1End: '11:45',
			nap2Start: '15:00',
			nap2End: '17:10',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Breakfast bowl',
			'Toast',
			'Soup',
			'Cereal',
			'Crackers',
			'Cookies',
			'Pot pie',
		],
		notes: ['Play date with Charlie'],
		poop: 1,
		sleep: {
			wakeUp: '07:05',
			nap1Start: '00:00',
			nap1End: '00:00',
			nap2Start: '13:00',
			nap2End: '16:20',
			bedTime: '20:30',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Cereal',
			'Cookies',
			'Apple',
			'Soup',
			'Crackers',
			'Pork roll',
			'Cake',
		],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '06:38',
			nap1Start: '09:10',
			nap1End: '12:30',
			nap2Start: '15:10',
			nap2End: '16:50',
			bedTime: '20:10',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Cereal',
			'Fruit',
			'Pizza',
			'Oatmeal',
			'Crackers',
			'Pretzels',
			'Noodles',
		],
		notes: [],
		poop: 1,
		sleep: {
			wakeUp: '06:00',
			nap1Start: '09:10',
			nap1End: '11:40',
			nap2Start: '14:30',
			nap2End: '16:10',
			bedTime: '21:10',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'French toast',
			'Fruit',
			'Pancakes',
			'Chips',
			'Orange',
			'Chicken',
			'Ice cream',
		],
		notes: ['Tylenol', 'Mothers bliss'],
		poop: 1,
		sleep: {
			wakeUp: '06:20',
			nap1Start: '09:40',
			nap1End: '11:40',
			nap2Start: '14:30',
			nap2End: '16:00',
			bedTime: '20:50',
		},
	},
	{
		date: '',
		userId: '',
		food: ['Pancakes', 'Fruit', 'Oatmeal', 'Cake', 'Cookies', 'Meatloaf'],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '06:20',
			nap1Start: '09:20',
			nap1End: '11:30',
			nap2Start: '15:15',
			nap2End: '17:00',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Waffles',
			'Yogurt',
			'Chicken fingers',
			'Crackers',
			'Fruit',
			'Ham',
		],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '07:00',
			nap1Start: '00:00',
			nap1End: '00:00',
			nap2Start: '15:00',
			nap2End: '16:10',
			bedTime: '21:00',
		},
	},
];
