module.exports = [
	{
		date: '',
		userId: '',
		food: ['Pancakes', 'Fruit', 'Pizza', 'Cookies', 'Meatloaf'],
		notes: ['Tylenol'],
		poop: 0,
		sleep: {
			wakeUp: '06:30',
			nap1Start: '10:00',
			nap1End: '11:45',
			nap2Start: '15:00',
			nap2End: '17:10',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Waffles',
			'Toast',
			'Hot dogs',
			'Cereal',
			'Crackers',
			'Cookies',
			'Pot pie',
		],
		notes: ['Play date with Charlie'],
		poop: 2,
		sleep: {
			wakeUp: '07:05',
			nap1Start: '09:45',
			nap1End: '11:20',
			nap2Start: '00:00',
			nap2End: '00:00',
			bedTime: '20:30',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Cereal',
			'Cookies',
			'Apple',
			'Soup',
			'Crackers',
			'Pork roll',
			'Ice cream',
		],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '06:58',
			nap1Start: '09:40',
			nap1End: '12:10',
			nap2Start: '15:30',
			nap2End: '16:30',
			bedTime: '20:40',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Pancakes',
			'Fruit',
			'Pizza',
			'Oatmeal',
			'Crackers',
			'Pretzels',
			'Noodles',
		],
		notes: [],
		poop: 1,
		sleep: {
			wakeUp: '07:00',
			nap1Start: '09:30',
			nap1End: '11:40',
			nap2Start: '15:00',
			nap2End: '16:10',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'French toast',
			'Fruit',
			'Pancakes',
			'Orange',
			'Chicken',
			'Ice cream',
		],
		notes: ['Tylenol', 'Mothers bliss'],
		poop: 0,
		sleep: {
			wakeUp: '06:10',
			nap1Start: '09:20',
			nap1End: '11:50',
			nap2Start: '14:50',
			nap2End: '16:10',
			bedTime: '20:30',
		},
	},
	{
		date: '',
		userId: '',
		food: ['Pancakes', 'Fruit', 'Oatmeal', 'Cake', 'Cookies', 'Meatloaf'],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '06:50',
			nap1Start: '09:40',
			nap1End: '11:20',
			nap2Start: '15:20',
			nap2End: '17:00',
			bedTime: '21:10',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Waffles',
			'Yogurt',
			'Chicken fingers',
			'Crackers',
			'Fruit',
			'Ham',
		],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '07:20',
			nap1Start: '10:00',
			nap1End: '11:30',
			nap2Start: '15:00',
			nap2End: '16:10',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: ['Pancakes', 'Fruit', 'Pizza', 'Cookies', 'Meatloaf'],
		notes: ['Tylenol'],
		poop: 0,
		sleep: {
			wakeUp: '06:30',
			nap1Start: '10:00',
			nap1End: '11:45',
			nap2Start: '15:00',
			nap2End: '17:10',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Waffles',
			'Toast',
			'Hot dogs',
			'Cereal',
			'Crackers',
			'Cookies',
			'Pot pie',
		],
		notes: ['Play date with Charlie'],
		poop: 2,
		sleep: {
			wakeUp: '07:05',
			nap1Start: '09:45',
			nap1End: '11:20',
			nap2Start: '00:00',
			nap2End: '00:00',
			bedTime: '20:30',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Cereal',
			'Cookies',
			'Apple',
			'Soup',
			'Crackers',
			'Pork roll',
			'Ice cream',
		],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '06:58',
			nap1Start: '09:40',
			nap1End: '12:10',
			nap2Start: '15:30',
			nap2End: '16:30',
			bedTime: '20:40',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Pancakes',
			'Fruit',
			'Pizza',
			'Oatmeal',
			'Crackers',
			'Pretzels',
			'Noodles',
		],
		notes: [],
		poop: 1,
		sleep: {
			wakeUp: '07:00',
			nap1Start: '09:30',
			nap1End: '11:40',
			nap2Start: '15:00',
			nap2End: '16:10',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'French toast',
			'Fruit',
			'Pancakes',
			'Orange',
			'Chicken',
			'Ice cream',
		],
		notes: ['Tylenol', 'Mothers bliss'],
		poop: 0,
		sleep: {
			wakeUp: '06:10',
			nap1Start: '09:20',
			nap1End: '11:50',
			nap2Start: '14:50',
			nap2End: '16:10',
			bedTime: '20:30',
		},
	},
	{
		date: '',
		userId: '',
		food: ['Pancakes', 'Fruit', 'Oatmeal', 'Cake', 'Cookies', 'Meatloaf'],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '06:50',
			nap1Start: '09:40',
			nap1End: '11:20',
			nap2Start: '15:20',
			nap2End: '17:00',
			bedTime: '21:10',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Waffles',
			'Yogurt',
			'Chicken fingers',
			'Crackers',
			'Fruit',
			'Ham',
		],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '07:20',
			nap1Start: '10:00',
			nap1End: '11:30',
			nap2Start: '15:00',
			nap2End: '16:10',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: ['Pancakes', 'Fruit', 'Pizza', 'Cookies', 'Meatloaf'],
		notes: ['Tylenol'],
		poop: 0,
		sleep: {
			wakeUp: '06:30',
			nap1Start: '10:00',
			nap1End: '11:45',
			nap2Start: '15:00',
			nap2End: '17:10',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Waffles',
			'Toast',
			'Hot dogs',
			'Cereal',
			'Crackers',
			'Cookies',
			'Pot pie',
		],
		notes: ['Play date with Charlie'],
		poop: 2,
		sleep: {
			wakeUp: '07:05',
			nap1Start: '09:45',
			nap1End: '11:20',
			nap2Start: '00:00',
			nap2End: '00:00',
			bedTime: '20:30',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Cereal',
			'Cookies',
			'Apple',
			'Soup',
			'Crackers',
			'Pork roll',
			'Ice cream',
		],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '06:58',
			nap1Start: '09:40',
			nap1End: '12:10',
			nap2Start: '15:30',
			nap2End: '16:30',
			bedTime: '20:40',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Pancakes',
			'Fruit',
			'Pizza',
			'Oatmeal',
			'Crackers',
			'Pretzels',
			'Noodles',
		],
		notes: [],
		poop: 1,
		sleep: {
			wakeUp: '07:00',
			nap1Start: '09:30',
			nap1End: '11:40',
			nap2Start: '15:00',
			nap2End: '16:10',
			bedTime: '21:00',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'French toast',
			'Fruit',
			'Pancakes',
			'Orange',
			'Chicken',
			'Ice cream',
		],
		notes: ['Tylenol', 'Mothers bliss'],
		poop: 0,
		sleep: {
			wakeUp: '06:10',
			nap1Start: '09:20',
			nap1End: '11:50',
			nap2Start: '14:50',
			nap2End: '16:10',
			bedTime: '20:30',
		},
	},
	{
		date: '',
		userId: '',
		food: ['Pancakes', 'Fruit', 'Oatmeal', 'Cake', 'Cookies', 'Meatloaf'],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '06:50',
			nap1Start: '09:40',
			nap1End: '11:20',
			nap2Start: '15:20',
			nap2End: '17:00',
			bedTime: '21:10',
		},
	},
	{
		date: '',
		userId: '',
		food: [
			'Waffles',
			'Yogurt',
			'Chicken fingers',
			'Crackers',
			'Fruit',
			'Ham',
		],
		notes: [],
		poop: 0,
		sleep: {
			wakeUp: '07:20',
			nap1Start: '10:00',
			nap1End: '11:30',
			nap2Start: '15:00',
			nap2End: '16:10',
			bedTime: '21:00',
		},
	},
];
